---
- name: Ensure configured taps are tapped
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Ensure configured homebrew packages are installed
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  with_items: "{{ homebrew_packages }}"

# Ansible 2.5 required for accept_external_apps
#- name: Install configured cask applications
#  homebrew_cask:
#    name: "{{ item }}"
#    state: present
#    accept_external_apps: true
#  with_items: "{{ homebrew_cask_apps }}"
