# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
if [ -d "/Users/{{ local_user }}/Library/Python/2.7/bin" ]; then
    PATH="/Users/{{ local_user }}/Library/Python/2.7/bin:$PATH"
fi

{% if powerline_enabled|bool %}
export POWERLINE_COMMAND=powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /Users/{{ local_user }}/Library/Python/2.7/lib/python/site-packages/powerline/bindings/bash/powerline.sh
{% endif %}
